# Generated by Django 4.0.3 on 2023-04-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='ticketform',
        ),
        migrations.AddField(
            model_name='ticketform',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_list', to='ticket.requestform'),
            preserve_default=False,
        ),
    ]
