# Generated by Django 4.0.3 on 2023-04-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_requestform_ticketform_ticketform_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketform',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
