# Generated by Django 4.0.3 on 2023-04-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticketform_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketform',
            name='response_text',
            field=models.TextField(default=''),
        ),
    ]
