# Generated by Django 4.0.3 on 2023-04-15 18:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reply', to='comment.reply'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_tag', to='comment.tag'),
        ),
    ]
