# Generated by Django 4.0.3 on 2023-04-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
