# Generated by Django 4.0.3 on 2023-04-19 09:46

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to='users')),
                ('firstName', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('lastName', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('username', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('birthday_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('birthday', birthday.fields.BirthdayField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True)),
                ('national_code', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('balance', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
