# Generated by Django 4.0.3 on 2023-03-17 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_role_manager_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}')]),
        ),
    ]
