# Generated by Django 4.0.3 on 2023-04-16 08:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritehotel',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='favoritehotel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='room',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='roomspace',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomspace',
            name='room',
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-rate']},
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='check_in_range',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='check_out_range',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='header',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='phone_numbers',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='reply_count',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='type',
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='floor_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='HotelManager', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rate',
            field=models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.DeleteModel(
            name='CancelReserve',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='FavoriteHotel',
        ),
        migrations.DeleteModel(
            name='Reserve',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='roomFacility',
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
        migrations.DeleteModel(
            name='RoomSpace',
        ),
    ]
