# Generated by Django 4.0.3 on 2023-04-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='price_per_day',
            field=models.IntegerField(default=None),
        ),
    ]
