# Generated by Django 4.0.3 on 2023-04-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_reserve_price_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='price_per_day',
        ),
    ]
