# Generated by Django 4.0.3 on 2023-04-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_remove_favoritehotel_hotel_remove_favoritehotel_user_and_more'),
        ('Hotel', '0003_remove_reserve_price_per_day'),
    ]

    operations = [
    ]
